kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubernetes-events-notifier.fullname" . }}
  labels:
    {{- include "kubernetes-events-notifier.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
      - pods/log
      - nodes
      - namespaces
      - events
    verbs:
      - get
      - list
      - watch
